# Generated by Django 5.0.4 on 2024-04-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm_epuletgepszet_app', '0002_price_offer_alter_job_description_alter_job_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_offer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
