# Generated by Django 5.0.4 on 2024-04-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm_epuletgepszet_app', '0003_price_offer_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_offer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='price_offer',
            name='subject',
            field=models.TextField(max_length=200),
        ),
    ]
